RedHatProductSecurity/openlcs

requirements/base.txt

Fix vulnerabilities

---

requirements/base.txt

To fix https://github.com/RedHatProductSecurity/openlcs/security/dependabot/16

Bump django minor version

---

openlcs/libs/common.py
openlcs/libs/download.py
openlcs/libs/kojiconnector.py
openlcs/libs/tests.py
openlcs/libs/unpack.py
openlcsd/flow/tasks.py

OLCS-194
- Check the container is a source container
- If it is not the source container, try to find if it has a mapping source container
- Download the source container and unpack it.

Find the source container, download and unpack

---

openlcs/libs/common.py
openlcs/libs/kojiconnector.py
openlcsd/flow/tasks.py

[OLCS-246](https://issues.redhat.com/browse/OLCS-246)
Fixes OLCS-246

Get remote source components of source container

---

openlcs/libs/common.py
openlcs/libs/corgi_handler.py
openlcs/libs/sc_handler.py
openlcs/libs/tests.py
openlcs/packages/mixins.py
openlcsd/flow/tasks.py

[OLCS-248](https://issues.redhat.com/browse/OLCS-248)
Fixes OLCS-248

Update code for getting and saving components form Corgi

---

containers/docker-openlcs/Dockerfile

Fix the issue of COPY failed in Dockerfile

---

openlcs/products/serializers.py

Release api bugfix

---

openlcs/libs/common.py
openlcs/libs/corgi_handler.py
openlcs/libs/kojiconnector.py
openlcs/libs/sc_handler.py
openlcs/libs/tests.py
openlcs/openlcs/settings.py
openlcs/packages/mixins.py
openlcs/packages/serializers.py
openlcs/packages/views.py
openlcs/products/management/commands/dump_corgi_components.py
openlcs/products/management/commands/load_from_corgi_components.py
openlcs/products/models.py
openlcs/utils/views.py
openlcsd/flow/tasks.py

[OLCS-230](https://issues.redhat.com/browse/OLCS-230)
[OLCS-231](https://issues.redhat.com/browse/OLCS-231)
[OLCS-232](https://issues.redhat.com/browse/OLCS-232)
[OLCS-233](https://issues.redhat.com/browse/OLCS-233)
[OLCS-263](https://issues.redhat.com/browse/OLCS-263)
[OLCS-264](https://issues.redhat.com/browse/OLCS-264)
Fixes OLCS-230
Fixes OLCS-231
Fixes OLCS-232
Fixes OLCS-233
Fixes OLCS-263
Fixes OLCS-264

Support containers that contain golang, pip, npm and yarn remote source

---

openlcs/openlcs/settings.py

[OLCS-261](https://issues.redhat.com/browse/OLCS-261)

Fix authentication issue

---

openlcs/libs/sc_handler.py

[OLCS-277](https://issues.redhat.com/browse/OLCS-277)
Fixes OLCS-277

Fix cannot find Golang app vendor source issue

---

openlcsd/flow/tasks.py

Update the remote source component type

---

openlcs/libs/common.py
openlcs/libs/kojiconnector.py
openlcs/libs/sc_handler.py
openlcs/openlcs/settings_local.py.sdist
openlcsd/flow/task_wrapper.py
openlcsd/flow/tasks.py

[OLCS-277](https://issues.redhat.com/browse/OLCS-277)
Fixes OLCS-277

Fix cannot find source issue

---

openlcs/libs/corgi_handler.py

There's security warning prompts with verify disabled.

ssl verify should not be disabled while making requests

---

openlcs/libs/corgi_handler.py
openlcs/libs/tests.py
openlcs/openlcs/urls.py
openlcs/packages/mixins.py
openlcs/packages/views.py
openlcsd/flow/tasks.py

[OLCS-251](https://issues.redhat.com/browse/OLCS-251)
Fixes OLCS-251

Get module components from corgi and save the components

---

openlcs/packages/views.py

[OLCS-272](https://issues.redhat.com/browse/OLCS-272)
Fixes OLCS-272

Allow filter on components API

---

openlcs/libs/common.py
openlcs/libs/sc_handler.py

[OLCS-292](https://issues.redhat.com/browse/OLCS-292)
Fixes OLCS-292

Find source for some special components

---

openlcs/packages/views.py
openlcsd/flow/tasks.py

[OLCS-274](https://issues.redhat.com/browse/OLCS-274)
Fixes OLCS-274

Fix files NoneType issue

---

openlcs/openlcs/settings.py

[OLCS-227](https://issues.redhat.com/browse/OLCS-227)
Fixes OLCS-227

The imported packages can't be deleted from QE packages

---

openlcsd/flow/tasks.py

[OLCS-286](https://issues.redhat.com/browse/OLCS-286)
Fixes OLCS-286

Fix save data message issue

---

.gitlab-ci.yml

[OLCS-314](https://issues.redhat.com/browse/OLCS-314)

Fix cannot build release image issue

---

openlcsd/flow/tasks.py

[OLCS-276](https://issues.redhat.com/browse/OLCS-276)
Fixes OLCS-276

(Fix) Incorrect archive type for container misc component

---

openlcs/tasks/serializers.py

Task endpoint extra field add taskmeta not exist check prevent query not exist situation

add taskmeta not exist check

---

openlcs/libs/common.py
openlcs/libs/kojiconnector.py
openlcs/libs/sc_handler.py
openlcs/libs/tests.py
openlcsd/flow/tasks.py

[OLCS-288](https://issues.redhat.com/browse/OLCS-288)
Fixes OLCS-288

Get the module components from brew and update workflow

---

openlcs/libs/sc_handler.py

[OLCS-336](https://issues.redhat.com/browse/OLCS-336)
Fixes OLCS-336

Update component type in srpm/container group components

---

openlcs/libs/driver.py
openlcs/libs/encrypt_decrypt.py
openlcs/openlcs/settings.py
openlcs/packages/serializers.py
openlcs/packages/views.py
openlcs/utils/views.py
openlcsd/flow/tasks.py
tests/functional/conftest.py

reduce get token frequency, child task use parent task token

---

openlcs/libs/sc_handler.py
openlcsd/flow/tasks.py

Add detailed log for source containers with missing components situation

---

openlcs/packages/mixins.py

avoid KeyError in /rest/v1/packageimporttransaction/ api

---

openlcs/tasks/views.py

Add SearchFilter in tasks endpoint, add DUPLICATE status to Field filter

---

openlcs/openlcs/urls.py
openlcs/packages/models.py
openlcs/packages/views.py
openlcs/utils/renderers.py
tests/functional/api/test_componentsubscription.py
tests/functional/database_data.json

Fixes OLCS-377
review along with https://github.com/RedHatProductSecurity/openlcs/pull/100
This patch adds docstring for newly added APIs and several api test cases.

Docs and test cases

---

openlcs/libs/corgi.py
openlcs/packages/models.py

Populate component purls for subscription

---

openlcs/libs/metadata.py
openlcs/libs/tests.py
openlcsd/flow/tasks.py
tests/functional/data/metadata/maven/xmltool-3.3.pom

The parser of below package types are updated:
RPM, PYPI, NPM/YARN, GOLANG, MAVEN

Update package metadata parsers

---

.gitlab-ci.yml
.pylintrc
containers/docker-ci/Dockerfile
containers/docker-openlcs/Dockerfile
openlcs/libs/corgi.py
openlcs/libs/driver.py
openlcs/products/management/commands/dump_corgi_components.py
requirements/base.txt
requirements/devel.txt

Fix vulnerabilities in openlcs image

---

openlcs/libs/driver.py
openlcsd/flow/tasks.py

Fix task post data timeout issue

---

requirements/base.txt

Fixes https://github.com/RedHatProductSecurity/openlcs/security/dependabot/18

Upgrade Django minor version

---

containers/docker-openlcs/bin/entrypoint-celery-beat.sh
openlcs/openlcs/settings.py
openlcsd/celeryconfig.py
openlcsd/flow/periodic_tasks.py
requirements/base.txt

add celery beat support

---

openlcs/libs/common.py
openlcs/libs/corgi.py

Extend corgi module with more rpm wraps.

---

openlcsd/flow/task_wrapper.py

There are chances the args[0] is not of dict type, it's up to the caller.

Fix task wrapper bug.

---

containers/docker-openlcs/docker-compose.yml
openlcs/openlcs/settings.py
openlcs/products/models.py
openlcs/products/views.py
openlcs/utils/views.py
requirements/base.txt

[OLCS-361](https://issues.redhat.com/browse/OLCS-361)
Fixes OLCS-361

Fix long time loading for release page

---

README.md
openlcs/libs/common.py
openlcs/libs/corgi.py
openlcs/openlcs/settings.py
openlcs/packages/serializers.py
openlcs/packages/views.py
openlcsd/flow/periodic_tasks.py
openlcsd/flow/tasks.py

Use corgi source

---

openlcs/libs/sc_handler.py

fixes [OLCS-435](https://issues.redhat.com/browse/OLCS-435)

Update the source of metadata

---

README.md
openlcs/libs/celery_helper.py
openlcs/openlcs/settings.py
openlcs/packages/serializers.py
openlcs/packages/views.py
openlcs/tasks/views.py
openlcsd/celeryconfig.py
openlcsd/flow/periodic_tasks.py
openlcsd/flow/tasks.py

Add celery task priority support

---

openlcsd/flow/tasks.py

Fix get package_nvr issue

---

openlcs/libs/corgi.py
openlcs/libs/tests.py

Hack to survive identical return data while get paginated.

---

openlcs/libs/corgi.py
openlcs/packages/mixins.py
openlcs/packages/models.py
openlcs/products/models.py
openlcsd/flow/tasks.py

Workflow update to allow sync scan to corgi

---

openlcs/libs/corgi.py

Set timeout for httpx client

---

openlcs/libs/celery_helper.py
openlcs/openlcs/settings.py
openlcsd/flow/tasks.py
tests/functional/conftest.py

Update use corgi source

---

openlcs/libs/corgi.py
openlcsd/flow/tasks.py

fixes [OLCS-456](https://issues.redhat.com/browse/OLCS-456)

Fix get incorrect component from corgi

---

openlcs/libs/common.py

fixes [OLCS-460](https://issues.redhat.com/browse/OLCS-460)

Fix remote source version issue

---

openlcs/libs/corgi.py
openlcs/libs/exceptions.py
openlcs/libs/tests.py
openlcsd/flow/core.py
openlcsd/flow/tasks.py

Missing binary container for source

---

openlcs/libs/common.py
openlcs/libs/corgi.py

Minimal data retrieval

---

openlcs/libs/kojiconnector.py
openlcs/openlcs/settings.py
openlcsd/flow/tasks.py

Fix cannot find remote source issue

---

openlcs/packages/views.py

Also fixes the HOSTNAME/rest/v1/ in docstring.

Indent the untolerable long lines.

---

openlcsd/flow/tasks.py

Fixes [OLCS-475](https://issues.redhat.com/browse/OLCS-475)

Not filter components data

---

openlcsd/flow/tasks.py

adjust timeout parameter when request packageimporttransaction API

---

openlcs/libs/corgi.py
openlcs/libs/tests.py
openlcsd/flow/tasks.py

Also refined/simplified various functions in corgi module

Reduce memory consumption while querying corgi in subscription

---

openlcsd/flow/tasks.py

Fixes [OLCS-495](https://issues.redhat.com/browse/OLCS-495)

Fix download remote source issue

---

openlcs/libs/common.py
openlcs/libs/corgi.py
openlcsd/flow/tasks.py

An attempt to deal with mass amount of components from subscriptions.

Workflow tuning

---

openlcsd/flow/tasks.py

Raise exception in case no component found.

---

openlcs/packages/mixins.py

Ignore conflicts when bulk_create data

---

openlcs/packages/mixins.py

Remove ignore_conflicts for some items

---

openlcs/libs/driver.py
openlcsd/flow/tasks.py

Reset default timeout

---

openlcs/utils/backends.py

Explicitly grant staff permission to worker nodes.

---

openlcs/authentication/middleware.py

ADD admin permission for manager user in admin list

---

openlcsd/flow/tasks.py

fixes [OLCS-529](https://issues.redhat.com/browse/OLCS-529)

Fix OLCS-529 for koji.GenericError

---

openlcs/libs/corgi.py

filter go-package component when get component from subscriptions

---

openlcs/packages/mixins.py
openlcs/packages/views.py
openlcsd/flow/tasks.py

Reduce time cost and possible concurrency problem when calling packageimporttransaction API, adjust timeout parameter

---

openlcs/libs/common.py
openlcs/libs/corgi.py
openlcs/libs/driver.py
openlcs/libs/tests.py
openlcs/packages/mixins.py
openlcs/packages/views.py
openlcsd/flow/tasks.py

Ability to determine env based on lib conf

---

openlcs/libs/celery_helper.py
openlcs/libs/constants.py
openlcs/libs/driver.py
openlcs/libs/exceptions.py

- Move exceptions to dedicated module
- Use separate module to hold constants.

Some minor improvements

---

openlcs/libs/common.py
openlcs/libs/corgi.py
openlcsd/flow/tasks.py

Use Corgi token when sync data to Corgi

---

openlcs/libs/corgi.py
openlcsd/flow/periodic_tasks.py
openlcsd/flow/tasks.py

Consume one subscription each time

---

requirements/base.txt

see https://github.com/RedHatProductSecurity/openlcs/security/dependabot/23

Fix depbot complaints

---

openlcs/openlcs/urls.py
openlcs/packages/serializers.py
openlcs/packages/views.py

Fixes [OLCS-618](https://issues.redhat.com/browse/OLCS-618)

Provide API endpoints for update periodic task schedule

---

openlcs/libs/corgi.py
openlcs/libs/sc_handler.py
openlcsd/flow/task_wrapper.py
openlcsd/flow/tasks.py

get parent oci component information when corgi download_url failed and no parent info found

---

requirements/base.txt

https://github.com/RedHatProductSecurity/openlcs/security/dependabot/24

Fix security bot complaints

---

openlcs/authentication/views.py

fixes [OLCS-644](https://issues.redhat.com/browse/OLCS-644)

Update token API doc strings

---

openlcs/packages/mixins.py
openlcs/reports/models.py
openlcsd/flow/tasks.py

performance optimize for save scan result part

---

openlcs/libs/common.py
openlcsd/flow/tasks.py

support corgi MAVEN component download_url

---

openlcs/libs/corgi.py

return purl when failed to get component info from corgi

---

openlcs/libs/common.py
openlcs/libs/corgi.py
openlcs/libs/tests.py
openlcsd/flow/tasks.py

Corgi component API change compatible

---

openlcs/packages/serializers.py
tests/integration/test_autoimport_workflow.py
tests/integration/test_retry.py

add retry workflow test case

---

openlcs/reports/serializers.py
tests/functional/api/test_componentsubscription.py
tests/functional/api/test_report.py
tests/functional/database_data.json

Get success scans

---

openlcs/reports/serializers.py
tests/functional/api/test_report.py
tests/functional/api/test_task.py
tests/functional/database_data.json

add complete count for metrics API

---

openlcs/reports/serializers.py
tests/functional/api/test_report.py

add failed_scans field to metric API
